version: "3.1"
services:
  redisedge:
    build: ./redisedge
    secrets:
      - azure_blob_secret
    ports:
      - 6379:6379
  droneapp60:
    build: ./app
    depends_on:
      - redisedge
    command: ['init.py', '--url', 'redis://redisedge:6379']
secrets:
  azure_blob_secret:
    file: ./redisedge/secrets/azureblobsecret.txt